// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW5zfVIHpB8p5IDMV5277qNmqJJXI4h1o',
    appId: '1:155334771870:web:a2ce325b8af00690a0678f',
    messagingSenderId: '155334771870',
    projectId: 'simplestockchecker',
    authDomain: 'simplestockchecker.firebaseapp.com',
    storageBucket: 'simplestockchecker.appspot.com',
    measurementId: 'G-1VZYSRE69S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVqAJZ1QR0fSWk_FkI95Ud9bgfL96rc2E',
    appId: '1:155334771870:android:659ab7b3ebeefcb5a0678f',
    messagingSenderId: '155334771870',
    projectId: 'simplestockchecker',
    storageBucket: 'simplestockchecker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHPKJDOBouGv0hsfoTrmU1StBE7mQNyEs',
    appId: '1:155334771870:ios:45d465b3cf72d32ba0678f',
    messagingSenderId: '155334771870',
    projectId: 'simplestockchecker',
    storageBucket: 'simplestockchecker.appspot.com',
    iosClientId: '155334771870-kkhkqaanerlep2jf79ld113imqb04a8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleStoreChecked',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHPKJDOBouGv0hsfoTrmU1StBE7mQNyEs',
    appId: '1:155334771870:ios:45d465b3cf72d32ba0678f',
    messagingSenderId: '155334771870',
    projectId: 'simplestockchecker',
    storageBucket: 'simplestockchecker.appspot.com',
    iosClientId: '155334771870-kkhkqaanerlep2jf79ld113imqb04a8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleStoreChecked',
  );
}
